<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Prana.Tools.Importer.Tests</RootNamespace>
    <AssemblyName>Prana.Tools.Importer.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\Prana.Tools.Importer\Prana.Tools.Importer.csproj" />
  </ItemGroup>

</Project>
